### ISSUE TITLE
some questions please.

### ISSUE THREAD

**Issue by agony09** [martinius96/Webwars#2]
Hello, I have a few questions about this script.
And I would be very happy to receive information.
- which PHP version on the server is recommended for this script?
- the "known bugs in game", will they be fixed in the future?
- will the game be developed further?
thank you and best regards

**Comment by martinius96** [comment]
Hi.
Game will run under PHP 7+ and under 5.6 too.
No, I will not fix game to future and no development will be made. 
It's now dead project :-)

**Comment by agony09** [comment]
ok, thank for answer
